"""test invitation id added

Revision ID: 01885a7f172f
Revises: bb73b5804663
Create Date: 2025-06-17 14:29:40.223609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01885a7f172f'
down_revision = 'bb73b5804663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.alter_column('clients',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.drop_column('test_id')

    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.alter_column('clients',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
