"""created referrals table, made changes to applicants table

Revision ID: 0e6f90a14695
Revises: 
Create Date: 2025-05-28 12:32:31.724612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6f90a14695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_fresher', sa.Boolean(), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('referenced_from', sa.String(length=100), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=255), nullable=True),
    sa.Column('github_profile', sa.String(length=255), nullable=True),
    sa.Column('is_kanaka_employee', sa.Boolean(), nullable=True),
    sa.Column('current_company', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('current_job_position', sa.String(length=100), nullable=True),
    sa.Column('current_ctc', sa.Integer(), nullable=True),
    sa.Column('expected_ctc', sa.Integer(), nullable=True),
    sa.Column('notice_period', sa.Integer(), nullable=True),
    sa.Column('tenure_at_current_company', sa.Integer(), nullable=True),
    sa.Column('current_offers', sa.Integer(), nullable=True),
    sa.Column('reason_for_change', sa.Text(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=500), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('is_referred', sa.Boolean(), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('referral_date', sa.Date(), nullable=True),
    sa.Column('cv_file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruitment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('test_scheduled', sa.Date(), nullable=True),
    sa.Column('test_result', sa.Boolean(), nullable=True),
    sa.Column('interview_round_1', sa.Date(), nullable=True),
    sa.Column('interview_round_1_comments', sa.Text(), nullable=True),
    sa.Column('interview_round_2', sa.Date(), nullable=True),
    sa.Column('interview_round_2_comments', sa.Text(), nullable=True),
    sa.Column('hr_round', sa.Date(), nullable=True),
    sa.Column('hr_round_comments', sa.Text(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'applicants', ['applicant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('recruitment_history')
    op.drop_table('referrals')
    op.drop_table('applicants')
    # ### end Alembic commands ###
