"""Added is_open column

Revision ID: 1285b0ef4faa
Revises: 97f980d94b6c
Create Date: 2025-06-09 16:29:14.888010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1285b0ef4faa'
down_revision = '97f980d94b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.drop_column('is_open')

    # ### end Alembic commands ###
