"""added relationship between referrals and applicants

Revision ID: 155e4adb1c3d
Revises: 1f6c94b50519
Create Date: 2025-06-05 10:45:17.074681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155e4adb1c3d'
down_revision = '1f6c94b50519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'applicants', ['applicant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('applicant_id')

    # ### end Alembic commands ###
