"""Added jobrequirements table

Revision ID: 1f6c94b50519
Revises: d245afd19f43
Create Date: 2025-06-04 11:51:20.183400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6c94b50519'
down_revision = 'd245afd19f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobrequirement',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_position', sa.String(length=50), nullable=False),
    sa.Column('job_desc', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jobrequirement', ['job_id'], ['job_id'])

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jobrequirement', ['job_id'], ['job_id'])

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jobrequirement', ['job_id'], ['job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    op.drop_table('jobrequirement')
    # ### end Alembic commands ###
