"""added rejected column to recruitment_history

Revision ID: 23117ee3619d
Revises: f72959c074f8
Create Date: 2025-05-27 11:06:45.098071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23117ee3619d'
down_revision = 'f72959c074f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.drop_column('rejected')

    # ### end Alembic commands ###
