"""Added new column in referral

Revision ID: 3fc70eb012f3
Revises: cee7bbe7befc
Create Date: 2025-07-15 12:00:48.569606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc70eb012f3'
down_revision = 'cee7bbe7befc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external_referrer', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('is_external_referrer')

    # ### end Alembic commands ###
