"""New test id column

Revision ID: 4b03da4aada6
Revises: 56ed320c31af
Create Date: 2025-06-12 11:49:48.206561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b03da4aada6'
down_revision = '56ed320c31af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
