"""Updated schema of recruitment_history table

Revision ID: 4e3ad22bab47
Revises: a76afa034ea6
Create Date: 2025-05-26 13:00:58.978347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3ad22bab47'
down_revision = 'a76afa034ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('current_stage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('cv_file_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_scheduled', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('test_result', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_1', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_1_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_2', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_2_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hr_round', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hr_round_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_stage', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'applicants', ['current_stage'], ['current_stage'])
        batch_op.drop_column('status')
        batch_op.drop_column('stage')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stage', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_stage')
        batch_op.drop_column('hr_round_comments')
        batch_op.drop_column('hr_round')
        batch_op.drop_column('interview_round_2_comments')
        batch_op.drop_column('interview_round_2')
        batch_op.drop_column('interview_round_1_comments')
        batch_op.drop_column('interview_round_1')
        batch_op.drop_column('test_result')
        batch_op.drop_column('test_scheduled')

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('cv_file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('current_stage',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
