"""column added

Revision ID: 523579acdeda
Revises: c13ecf0b9094
Create Date: 2025-07-23 17:26:37.168200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523579acdeda'
down_revision = 'c13ecf0b9094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('designation')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external_referrer', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('is_external_referrer')

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
