"""Added test time

Revision ID: 56ed320c31af
Revises: 1285b0ef4faa
Create Date: 2025-06-11 16:29:06.523334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56ed320c31af'
down_revision = '1285b0ef4faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_time', sa.Time(), nullable=True))
        batch_op.alter_column('test_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.alter_column('test_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('test_time')

    # ### end Alembic commands ###
