"""empty message

Revision ID: 62c99c7dc153
Revises: f64761d31e77
Create Date: 2025-05-26 15:51:31.020851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62c99c7dc153'
down_revision = 'f64761d31e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
