"""empty message

Revision ID: 66925b7997df
Revises: 66ce8164d97b
Create Date: 2025-05-23 15:56:19.615735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66925b7997df'
down_revision = '66ce8164d97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('applied_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('applied_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
