"""DB updated

Revision ID: 68fe2ab8dc43
Revises: 
Create Date: 2025-07-24 04:16:12.443908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fe2ab8dc43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('designation')

    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.alter_column('skillset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external_referrer', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin_profile')
        batch_op.drop_column('designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linkedin_profile', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('is_external_referrer')

    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.alter_column('skillset',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
