"""Added fresher status to referral table

Revision ID: 78443d5799bb
Revises: 9f34db85efcb
Create Date: 2025-06-09 14:46:28.532636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78443d5799bb'
down_revision = '9f34db85efcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fresher', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('is_fresher')

    # ### end Alembic commands ###
