"""Auth type added to users

Revision ID: 804abb6b8d9e
Revises: 4b03da4aada6
Create Date: 2025-06-16 11:06:14.832543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804abb6b8d9e'
down_revision = '4b03da4aada6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_type')

    # ### end Alembic commands ###
