"""Added scheduler info to interviews.py

Revision ID: 8ca818a8c44e
Revises: 742f21b27cd4
Create Date: 2025-05-30 10:35:27.118576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca818a8c44e'
down_revision = '742f21b27cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduler_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['scheduler_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('scheduler_id')

    # ### end Alembic commands ###
