"""Added is_open column

Revision ID: 97f980d94b6c
Revises: 47d124104151
Create Date: 2025-06-09 16:28:37.350644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f980d94b6c'
down_revision = '47d124104151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.drop_column('is_open')

    # ### end Alembic commands ###
