"""Adding feedback column

Revision ID: 98790298ca4e
Revises: d8a4e1a7e496
Create Date: 2025-06-24 11:07:03.853328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98790298ca4e'
down_revision = 'd8a4e1a7e496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.alter_column('round_number',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('round_number',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
