"""Increase role column size to 20

Revision ID: 9c021080ffc2
Revises: 5be68193b167
Create Date: 2025-05-22 14:30:06.651554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c021080ffc2'
down_revision = '5be68193b167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('applied_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('submitted_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'applicants', ['comments'], ['comments'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('submitted_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('applied_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
