"""Added applied_date to history, renamed applied_date to last_applied

Revision ID: a759144186cc
Revises: 8ca818a8c44e
Create Date: 2025-05-30 14:04:39.040071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a759144186cc'
down_revision = '8ca818a8c44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.drop_column('applied_date')

    # ### end Alembic commands ###
