"""Added referred_by column

Revision ID: a76afa034ea6
Revises: ae39ede0aad3
Create Date: 2025-05-23 16:31:30.151884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76afa034ea6'
down_revision = 'ae39ede0aad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referred_by')

    # ### end Alembic commands ###
