"""Initial migration

Revision ID: bb73b5804663
Revises: 804abb6b8d9e
Create Date: 2025-06-17 10:49:49.291323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb73b5804663'
down_revision = '804abb6b8d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('linkedin_profile', sa.Text(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('password_changed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobrequirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skillset', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('clients', sa.Text(), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('native_place', sa.String(length=100), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('is_fresher', sa.Boolean(), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('current_internship', sa.Boolean(), nullable=True),
    sa.Column('internship_duration', sa.Integer(), nullable=True),
    sa.Column('paid_internship', sa.Boolean(), nullable=True),
    sa.Column('stipend', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('referenced_from', sa.String(length=100), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=255), nullable=True),
    sa.Column('github_profile', sa.String(length=255), nullable=True),
    sa.Column('is_kanaka_employee', sa.Boolean(), nullable=True),
    sa.Column('current_company', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('current_job_position', sa.String(length=100), nullable=True),
    sa.Column('current_ctc', sa.Integer(), nullable=True),
    sa.Column('expected_ctc', sa.Integer(), nullable=True),
    sa.Column('notice_period', sa.Integer(), nullable=True),
    sa.Column('tenure_at_current_company', sa.Text(), nullable=True),
    sa.Column('current_offers_yes_no', sa.Boolean(), nullable=True),
    sa.Column('current_offers_description', sa.Text(), nullable=True),
    sa.Column('reason_for_change', sa.Text(), nullable=True),
    sa.Column('last_applied', sa.Date(), nullable=True),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('is_referred', sa.Boolean(), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobrequirement.id'], ),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('scheduler_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobrequirement.id'], ),
    sa.ForeignKeyConstraint(['scheduler_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruitment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('test_time', sa.Time(), nullable=True),
    sa.Column('test_result', sa.Boolean(), nullable=True),
    sa.Column('interview_round_1_date', sa.Date(), nullable=True),
    sa.Column('interview_round_1_time', sa.Time(), nullable=True),
    sa.Column('interview_round_1_comments', sa.Text(), nullable=True),
    sa.Column('interview_round_2_date', sa.Date(), nullable=True),
    sa.Column('interview_round_2_time', sa.Time(), nullable=True),
    sa.Column('interview_round_2_comments', sa.Text(), nullable=True),
    sa.Column('hr_round_date', sa.Date(), nullable=True),
    sa.Column('hr_round_time', sa.Time(), nullable=True),
    sa.Column('hr_round_comments', sa.Text(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('referred_by', sa.Text(), nullable=True),
    sa.Column('referral_date', sa.Date(), nullable=True),
    sa.Column('cv_file_path', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('is_fresher', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobrequirement.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('recruitment_history')
    op.drop_table('interviews')
    op.drop_table('applicants')
    op.drop_table('jobrequirement')
    op.drop_table('users')
    # ### end Alembic commands ###
