"""remove the designation and linkedin field from user profile

Revision ID: c13ecf0b9094
Revises: 3fc70eb012f3
Create Date: 2025-07-18 15:12:28.705888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13ecf0b9094'
down_revision = '3fc70eb012f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('designation')
        batch_op.drop_column('linkedin_profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_profile', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
