"""Added created_by_id column and added relationship for the same

Revision ID: c3677b760bb6
Revises: d4bfe1d1140a
Create Date: 2025-06-06 12:38:32.118636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3677b760bb6'
down_revision = 'd4bfe1d1140a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
