"""added internship details, updated location details

Revision ID: c3fcb1ca9e0c
Revises: 2e45481f89ee
Create Date: 2025-06-02 10:50:37.873299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fcb1ca9e0c'
down_revision = '2e45481f89ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_place', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_internship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('internship_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paid_internship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stipend', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_offers_description', sa.Text(), nullable=True))
        batch_op.alter_column('tenure_at_current_company',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('current_offers',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.alter_column('current_offers',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('tenure_at_current_company',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('current_offers_description')
        batch_op.drop_column('work_location')
        batch_op.drop_column('stipend')
        batch_op.drop_column('paid_internship')
        batch_op.drop_column('internship_duration')
        batch_op.drop_column('current_internship')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('native_place')

    # ### end Alembic commands ###
