"""empty message

Revision ID: cee7bbe7befc
Revises: 98790298ca4e
Create Date: 2025-07-10 12:39:39.983886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee7bbe7befc'
down_revision = '98790298ca4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
