"""changed candidate_id to name in referrals.py

Revision ID: cfdbbded53e1
Revises: 2c1b0f7c83a3
Create Date: 2025-05-28 14:04:29.687103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdbbded53e1'
down_revision = '2c1b0f7c83a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('candidate_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
