"""added internship details, updated location details

Revision ID: d245afd19f43
Revises: eeb51595e6d3
Create Date: 2025-06-02 10:57:01.832245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd245afd19f43'
down_revision = 'eeb51595e6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_place', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_internship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('internship_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paid_internship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stipend', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_offers_yes_no', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('current_offers_description', sa.Text(), nullable=True))
        batch_op.alter_column('tenure_at_current_company',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('current_offers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_offers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('tenure_at_current_company',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('current_offers_description')
        batch_op.drop_column('current_offers_yes_no')
        batch_op.drop_column('work_location')
        batch_op.drop_column('stipend')
        batch_op.drop_column('paid_internship')
        batch_op.drop_column('internship_duration')
        batch_op.drop_column('current_internship')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('native_place')

    # ### end Alembic commands ###
