"""added time to interviews.py

Revision ID: d47671d12e86
Revises: e771f706e560
Create Date: 2025-05-28 15:53:03.186915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47671d12e86'
down_revision = 'e771f706e560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
