"""Changed column name

Revision ID: d4bfe1d1140a
Revises: 155e4adb1c3d
Create Date: 2025-06-05 16:48:37.332916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bfe1d1140a'
down_revision = '155e4adb1c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=False))
        batch_op.drop_column('job_desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_desc', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###
