"""empty message

Revision ID: de7fc142e77b
Revises: cfdbbded53e1
Create Date: 2025-05-28 14:15:18.313187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7fc142e77b'
down_revision = 'cfdbbded53e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('referred_by')

    # ### end Alembic commands ###
