"""tables updating 

Revision ID: e2779815ead0
Revises: 5822df0a9ba7
Create Date: 2025-06-26 16:50:44.807546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2779815ead0'
down_revision = '5822df0a9ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.alter_column('round_number',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_vendor', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('auth_type')

    with op.batch_alter_table('jobrequirement', schema=None) as batch_op:
        batch_op.drop_column('for_vendor')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('round_number',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
