"""added interview timing columns

Revision ID: e771f706e560
Revises: e0ff6a1a1a74
Create Date: 2025-05-28 15:51:43.363162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e771f706e560'
down_revision = 'e0ff6a1a1a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_round_1_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_1_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_2_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_round_2_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hr_round_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hr_round_time', sa.Time(), nullable=True))
        batch_op.drop_column('hr_round')
        batch_op.drop_column('interview_round_1')
        batch_op.drop_column('interview_round_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_round_2', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interview_round_1', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hr_round', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('hr_round_time')
        batch_op.drop_column('hr_round_date')
        batch_op.drop_column('interview_round_2_time')
        batch_op.drop_column('interview_round_2_date')
        batch_op.drop_column('interview_round_1_time')
        batch_op.drop_column('interview_round_1_date')

    # ### end Alembic commands ###
